{% set version = "1.2.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-randomfieldsutils
  version: {{ version|replace("-", "_") }}

source:
  fn: RandomFieldsUtils_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/RandomFieldsUtils_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RandomFieldsUtils/RandomFieldsUtils_{{ version }}.tar.gz
  sha256: 588dc688f674292b13ee55df57945df2630e4efe0121a53528c869dd603fe8b6

build:
  merge_build_host: true  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ compiler('m2w64_fortran') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - llvm-openmp                # [osx]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - llvm-openmp                # [osx]

test:
  commands:
    - $R -e "library('RandomFieldsUtils')"           # [not win]
    - "\"%R%\" -e \"library('RandomFieldsUtils')\""  # [win]

about:
  home: http://ms.math.uni-mannheim.de/de/publications/software
  license: GPL-3.0-or-later
  summary: Various utilities are provided that might be used in spatial statistics and elsewhere. It delivers a method for solving linear equations that checks the sparsity of the matrix before any algorithm is used. Furthermore, it includes the Struve functions.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
