appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: i1Ko+d5GlEbLmUFUZ4r9y8wghQb55o9A/yx2Kjtojz6LzeWsnC8tOi6JFN7voWb0YBtZjPQ9jDo7OBTYpBM/b4oRSOkkqBTO5Sh5dv+DUJuIQnuzuFI80Tj6mAr1AkpCZHwIgdIsO8QgwceUPvrtf3BrWsVxeE06Z5Seqo638bDS95xcn7QGxMMq5v+18go5Fn5u7kveyLMzolDeLrvtO4BYslX/9PcQmNA9ns1ynAoGY2SZKN3lrhnZm26ksN8L//MIW9YxA95DSHfg+ZhiQdVGRJd9c7lD/ke8Db6jb9ZMgF57+ojKXWLm1IppXMkK6bQcuwFPRSZNSuURgweiwOmtAyUwhhixeKrJFvy8vLz+dtcpXlNeRdE8LExrGECM9hLP4KGvX0wm77r4sM9YZSwG/fzsQCw6sqzbXf9SyjN7QmPJxRruru1v/BOQS8+ohORhDIfirMrPsj6rwbHdyd9wWYx7wgp25QO30JBjgzrIereMv4ef6bG0NNC2ogdoITPCL5745YKiYU8iajwSKQ8xO2rmQcWPfGPngN3BvAML1dXDYFCK0xUzpJcJ4XfAftlS619m1Psxw3oXXsvpLoL/o7vlKZswq/aXi/ElZG6pM86im0Yf6uQmkkaxrHGOBgqUjYDcaOJAtl2XTcR9yEDTD+wBR8BiENslIuzRmXo=}
