travis:
  secure:
    BINSTAR_TOKEN: eyrTylyoEP4ch4r3/x0FW39oiI6vCCnvbB4STmDkYoQcLynpOefZyxcGs6D8X4Rq6otD9Y5oSFvGnXTkWa5wfCbpsA+VY6GyupUntUpL2bT4EcejV4fWhQD6opt6awN/D2bhkzqSWq5TN+RxhlNgK536dqU3iCtJE9I5LvJ9g7JKar5W+e+E3W3txNzZ1z7MCV8bJ4GCHrPCgV1O2x9AaB5BR8RmMDY0FA+mCfMMKrvmiQydKtWe5F4beDnQ0UOPJyOoaRIPOhsZBLmZukxU84LPP5GqysPRryqPhwF4bWFrZrG24+1Feke+P+5ZmWLCWD9YU93zKlKZiT6SM0bJ72sfgjeZNMKwIMSgJ6i7Fn2QplK8ycFiPvRRHfu3Z0GHQBLVHMTdKT49EeqChKU49NQOKHe4g2hXas1sB6+K+WihejGSOvyJm9k3tp68OCWgR0C1oGJgTQUnOy1KWye+xRAGdAYb40J9++IxoWz7fOdSNE/C0zMc4ptkdNnwKWYyqz8ardXn5gf9A8UAb1QM3kn7Ss2e8pWkYUqUBT3tRpExhRolztomB2KN+Mnjv4e5aU3b7qIqFrCGNs9kFfemuPnCWuXmj4WVEA/ApxZLp7LjyF2GE6nbmL+WsMT/LdqA2ZU5TBep9y4VCDg5QeY/3NFgDvi/e0Oy4/Uyp5x8I1c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
